In [38]:
import numpy as np
import pandas as pd

In [39]:
df = pd.read_csv("Final_Merged.csv")

In [40]:
df

,address,in_btc,out_btc,balance,in_degree,out_degree,unique_in_degree,unique_out_degree,mean_in_btc,mean_out_btc,...,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
0,19snqSYnDSC4mDbv3pJuYgYqm5ctqwAxnm,50.000000,50.000000,0.0,1,1,1,2,50.000000,50.000000,...,50.000000,37.428937,12.571063,0.000000,12.428937,0.111111,0.111111,5.555556,5.555556,0
1,1FeGY25MSKtnwVNGrnbwLsecBpBYrMQ6Kx,50.000000,50.000000,0.0,1,1,1,2,50.000000,50.000000,...,50.000000,43.011620,6.988380,0.000000,18.011620,1.000000,1.000000,50.000000,50.000000,0
2,1A1nkBK7tfnVRtVbyiirEWRcayQtSTBCsW,9.150000,9.150000,0.0,1,1,1,2,9.150000,9.150000,...,9.150000,7.700000,1.450000,0.000000,3.125000,1.000000,1.000000,9.150000,9.150000,0
3,18wHa1PLzoU4ToemBZn2czZbVEbyZJ2gSi,340.250000,340.250000,0.0,1,1,1,2,340.250000,340.250000,...,340.250000,340.200000,0.050000,0.000000,170.075000,1.000000,1.000000,340.250000,340.250000,0
4,188sYyuK756uEsq5LTk9tiXyJHeEjxKT5c,127.510000,127.510000,0.0,1,1,1,2,127.510000,127.510000,...,127.510000,127.460000,0.050000,0.000000,63.705000,1.000000,1.000000,127.510000,127.510000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51675,1NEDowT7w4kMFhwv2EARsvj98UPTM88n8E,61.575721,61.575721,0.0,49,49,4,96,1.256647,1.256647,...,0.108199,10.000000,0.000004,1.584554,1.019205,0.266304,0.266304,0.334651,0.334651,1
51676,1NEehsUcB3e5gzXNngjYtpgBEKZDLdm1wR,2.000000,2.000000,0.0,1,1,4,1,2.000000,2.000000,...,0.048780,1.999807,0.000193,0.327910,0.999807,1.000000,1.000000,2.000000,2.000000,1
51677,1NEgxsitmSW3Spyv9GRGZZgvRYGU84oBzb,1.000000,1.000000,0.0,1,1,3,2,1.000000,1.000000,...,0.006514,0.999621,0.000007,0.455300,0.471136,1.000000,1.000000,1.000000,1.000000,1
51678,1NeiGxRsrXXg1yv81Ch6QEEVft46wpEY2G,2.400000,2.400000,0.0,2,2,2,4,1.200000,1.200000,...,1.200000,1.199887,0.000013,0.000000,0.565291,0.166667,0.166667,0.200000,0.200000,1
51679,1NEkqoKaJB98ZidfDM5UvX81kabcY5RQVX,0.519400,0.519400,0.0,1,1,1,1,0.519400,0.519400,...,0.519400,0.519194,0.000206,0.000000,0.259494,1.000000,1.000000,0.519400,0.519400,1

In [41]:
df[df["is_Malicious"] == 1]

,address,in_btc,out_btc,balance,in_degree,out_degree,unique_in_degree,unique_out_degree,mean_in_btc,mean_out_btc,...,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
33296,111K8kZAEnJg245r2cM6y9zgJGHZtJPy6,1.000500,1.000500,0.0,1,1,1,1,1.000500,1.000500,...,1.000500,1.000209,0.000291,0.000000,0.499959,1.000000,1.000000,1.000500,1.000500,1
33297,1123pJv8jzeFQaCV4w644pzQJzVWay2zcA,1.000000,1.000000,0.0,1,1,1,2,1.000000,1.000000,...,1.000000,0.999765,0.000032,0.000000,0.471238,0.142857,0.142857,0.142857,0.142857,1
33298,112536im7hy6wtKbpH1qYDWtTyMRAcA2p7,2.000000,2.000000,0.0,1,1,12,1,2.000000,2.000000,...,0.087061,1.999712,0.000288,0.024002,0.999712,1.000000,1.000000,2.000000,2.000000,1
33299,1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7,0.712000,0.712000,0.0,1,1,1,1,0.712000,0.712000,...,0.712000,0.711706,0.000294,0.000000,0.355706,1.000000,1.000000,0.712000,0.712000,1
33300,1129TSjKtx65E35GiUo4AYVeyo48twbrGX,2.000000,2.000000,0.0,1,1,1,2,2.000000,2.000000,...,2.000000,1.999773,0.000055,0.000000,0.942648,1.000000,1.000000,2.000000,2.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51675,1NEDowT7w4kMFhwv2EARsvj98UPTM88n8E,61.575721,61.575721,0.0,49,49,4,96,1.256647,1.256647,...,0.108199,10.000000,0.000004,1.584554,1.019205,0.266304,0.266304,0.334651,0.334651,1
51676,1NEehsUcB3e5gzXNngjYtpgBEKZDLdm1wR,2.000000,2.000000,0.0,1,1,4,1,2.000000,2.000000,...,0.048780,1.999807,0.000193,0.327910,0.999807,1.000000,1.000000,2.000000,2.000000,1
51677,1NEgxsitmSW3Spyv9GRGZZgvRYGU84oBzb,1.000000,1.000000,0.0,1,1,3,2,1.000000,1.000000,...,0.006514,0.999621,0.000007,0.455300,0.471136,1.000000,1.000000,1.000000,1.000000,1
51678,1NeiGxRsrXXg1yv81Ch6QEEVft46wpEY2G,2.400000,2.400000,0.0,2,2,2,4,1.200000,1.200000,...,1.200000,1.199887,0.000013,0.000000,0.565291,0.166667,0.166667,0.200000,0.200000,1
51679,1NEkqoKaJB98ZidfDM5UvX81kabcY5RQVX,0.519400,0.519400,0.0,1,1,1,1,0.519400,0.519400,...,0.519400,0.519194,0.000206,0.000000,0.259494,1.000000,1.000000,0.519400,0.519400,1

In [42]:
df.describe()

,in_btc,out_btc,balance,in_degree,out_degree,unique_in_degree,unique_out_degree,mean_in_btc,mean_out_btc,max_in_btc,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
count,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,5.168000e+04,51680.000000,5.168000e+04,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000,51680.000000
mean,371.859113,371.011081,0.848032,18.226974,6.660507,22.054238,9.188467,60.092650,77.799733,105.086371,3.708921e+01,147.732889,1.302980e+01,14.202191,40.775094,0.892943,0.825538,39.362353,39.361560,0.355728
std,4190.703010,4190.562570,35.215184,147.027592,110.223016,201.089812,189.386287,733.387479,1951.555088,2377.100216,3.271396e+02,2591.705939,7.112740e+02,697.911005,695.528759,1.612080,0.988917,722.131251,722.131290,0.478738
min,0.300000,0.030000,-3.500000,1.000000,1.000000,1.000000,1.000000,0.010650,0.011145,0.010000,7.444460e-15,0.030000,2.371314e-15,0.000000,0.000000,0.000235,0.000235,0.000089,0.000013,0.000000
25%,1.200000,1.200000,0.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,3.916706e-01,1.009153,1.653750e-04,0.000000,0.450000,0.688623,0.500000,0.750000,0.750000,0.000000
50%,9.219213,9.040000,0.000000,1.000000,1.000000,1.000000,2.000000,4.000000,5.000000,5.000000,1.940000e+00,6.000000,3.000000e-02,0.000000,1.885218,1.000000,1.000000,2.500000,2.500000,0.000000
75%,48.180000,48.080000,0.000000,1.000000,1.000000,2.000000,2.000000,42.910000,44.972500,45.070000,3.903000e+01,46.100000,5.500000e-01,0.155047,21.345000,1.000000,1.000000,38.830000,38.830000,1.000000
max,400000.013920,400000.000000,4175.770911,7915.000000,7003.000000,34038.000000,12213.000000,83333.353333,400000.000000,250000.000000,4.559295e+04,250000.000000,1.500000e+05,117851.116056,74500.000000,226.000000,128.000000,151000.000000,151000.000000,1.000000

#### Handling Outliers

In [43]:
df = df[df["balance"] >= 0]
df

,address,in_btc,out_btc,balance,in_degree,out_degree,unique_in_degree,unique_out_degree,mean_in_btc,mean_out_btc,...,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
0,19snqSYnDSC4mDbv3pJuYgYqm5ctqwAxnm,50.000000,50.000000,0.0,1,1,1,2,50.000000,50.000000,...,50.000000,37.428937,12.571063,0.000000,12.428937,0.111111,0.111111,5.555556,5.555556,0
1,1FeGY25MSKtnwVNGrnbwLsecBpBYrMQ6Kx,50.000000,50.000000,0.0,1,1,1,2,50.000000,50.000000,...,50.000000,43.011620,6.988380,0.000000,18.011620,1.000000,1.000000,50.000000,50.000000,0
2,1A1nkBK7tfnVRtVbyiirEWRcayQtSTBCsW,9.150000,9.150000,0.0,1,1,1,2,9.150000,9.150000,...,9.150000,7.700000,1.450000,0.000000,3.125000,1.000000,1.000000,9.150000,9.150000,0
3,18wHa1PLzoU4ToemBZn2czZbVEbyZJ2gSi,340.250000,340.250000,0.0,1,1,1,2,340.250000,340.250000,...,340.250000,340.200000,0.050000,0.000000,170.075000,1.000000,1.000000,340.250000,340.250000,0
4,188sYyuK756uEsq5LTk9tiXyJHeEjxKT5c,127.510000,127.510000,0.0,1,1,1,2,127.510000,127.510000,...,127.510000,127.460000,0.050000,0.000000,63.705000,1.000000,1.000000,127.510000,127.510000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51675,1NEDowT7w4kMFhwv2EARsvj98UPTM88n8E,61.575721,61.575721,0.0,49,49,4,96,1.256647,1.256647,...,0.108199,10.000000,0.000004,1.584554,1.019205,0.266304,0.266304,0.334651,0.334651,1
51676,1NEehsUcB3e5gzXNngjYtpgBEKZDLdm1wR,2.000000,2.000000,0.0,1,1,4,1,2.000000,2.000000,...,0.048780,1.999807,0.000193,0.327910,0.999807,1.000000,1.000000,2.000000,2.000000,1
51677,1NEgxsitmSW3Spyv9GRGZZgvRYGU84oBzb,1.000000,1.000000,0.0,1,1,3,2,1.000000,1.000000,...,0.006514,0.999621,0.000007,0.455300,0.471136,1.000000,1.000000,1.000000,1.000000,1
51678,1NeiGxRsrXXg1yv81Ch6QEEVft46wpEY2G,2.400000,2.400000,0.0,2,2,2,4,1.200000,1.200000,...,1.200000,1.199887,0.000013,0.000000,0.565291,0.166667,0.166667,0.200000,0.200000,1
51679,1NEkqoKaJB98ZidfDM5UvX81kabcY5RQVX,0.519400,0.519400,0.0,1,1,1,1,0.519400,0.519400,...,0.519400,0.519194,0.000206,0.000000,0.259494,1.000000,1.000000,0.519400,0.519400,1

In [44]:
df[df["out_degree"] < 0]

Empty DataFrame
Columns: [address, in_btc, out_btc, balance, in_degree, out_degree, unique_in_degree, unique_out_degree, mean_in_btc, mean_out_btc, first_active, last_active, max_in_btc, min_in_btc, max_out_btc, min_out_btc, in_standard_deviation, out_standard_deviation, in_transaction_frequency, out_transaction_frequency, in_amount_frequency, out_amount_frequency, is_Malicious]
Index: []

[0 rows x 23 columns]

In [45]:
df[df["in_degree"] < 0]

Empty DataFrame
Columns: [address, in_btc, out_btc, balance, in_degree, out_degree, unique_in_degree, unique_out_degree, mean_in_btc, mean_out_btc, first_active, last_active, max_in_btc, min_in_btc, max_out_btc, min_out_btc, in_standard_deviation, out_standard_deviation, in_transaction_frequency, out_transaction_frequency, in_amount_frequency, out_amount_frequency, is_Malicious]
Index: []

[0 rows x 23 columns]

In [46]:
df["is_malicious"] = df["is_Malicious"]
df = df.drop(["is_Malicious"], axis = 1)
df

In [47]:
df["address"].describe()

count                                  51679
unique                                 47150
top       1JhXNL9wfV7RfF5GourYkhLt8j3yq8vfhs
freq                                      41
Name: address, dtype: object

In [48]:
df = df.drop_duplicates(subset=["address"])
df

,address,in_btc,out_btc,balance,in_degree,out_degree,unique_in_degree,unique_out_degree,mean_in_btc,mean_out_btc,...,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
0,19snqSYnDSC4mDbv3pJuYgYqm5ctqwAxnm,50.000000,50.000000,0.0,1,1,1,2,50.000000,50.000000,...,50.000000,37.428937,12.571063,0.000000,12.428937,0.111111,0.111111,5.555556,5.555556,0
1,1FeGY25MSKtnwVNGrnbwLsecBpBYrMQ6Kx,50.000000,50.000000,0.0,1,1,1,2,50.000000,50.000000,...,50.000000,43.011620,6.988380,0.000000,18.011620,1.000000,1.000000,50.000000,50.000000,0
2,1A1nkBK7tfnVRtVbyiirEWRcayQtSTBCsW,9.150000,9.150000,0.0,1,1,1,2,9.150000,9.150000,...,9.150000,7.700000,1.450000,0.000000,3.125000,1.000000,1.000000,9.150000,9.150000,0
3,18wHa1PLzoU4ToemBZn2czZbVEbyZJ2gSi,340.250000,340.250000,0.0,1,1,1,2,340.250000,340.250000,...,340.250000,340.200000,0.050000,0.000000,170.075000,1.000000,1.000000,340.250000,340.250000,0
4,188sYyuK756uEsq5LTk9tiXyJHeEjxKT5c,127.510000,127.510000,0.0,1,1,1,2,127.510000,127.510000,...,127.510000,127.460000,0.050000,0.000000,63.705000,1.000000,1.000000,127.510000,127.510000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51675,1NEDowT7w4kMFhwv2EARsvj98UPTM88n8E,61.575721,61.575721,0.0,49,49,4,96,1.256647,1.256647,...,0.108199,10.000000,0.000004,1.584554,1.019205,0.266304,0.266304,0.334651,0.334651,1
51676,1NEehsUcB3e5gzXNngjYtpgBEKZDLdm1wR,2.000000,2.000000,0.0,1,1,4,1,2.000000,2.000000,...,0.048780,1.999807,0.000193,0.327910,0.999807,1.000000,1.000000,2.000000,2.000000,1
51677,1NEgxsitmSW3Spyv9GRGZZgvRYGU84oBzb,1.000000,1.000000,0.0,1,1,3,2,1.000000,1.000000,...,0.006514,0.999621,0.000007,0.455300,0.471136,1.000000,1.000000,1.000000,1.000000,1
51678,1NeiGxRsrXXg1yv81Ch6QEEVft46wpEY2G,2.400000,2.400000,0.0,2,2,2,4,1.200000,1.200000,...,1.200000,1.199887,0.000013,0.000000,0.565291,0.166667,0.166667,0.200000,0.200000,1
51679,1NEkqoKaJB98ZidfDM5UvX81kabcY5RQVX,0.519400,0.519400,0.0,1,1,1,1,0.519400,0.519400,...,0.519400,0.519194,0.000206,0.000000,0.259494,1.000000,1.000000,0.519400,0.519400,1

In [49]:
df = df.reset_index()

In [51]:
df = df.drop(["level_0","index"], axis = 1)
df

In [52]:
df.describe()

,index,in_btc,out_btc,balance,in_degree,out_degree,unique_in_degree,unique_out_degree,mean_in_btc,mean_out_btc,...,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
count,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,...,4.715000e+04,47150.000000,4.715000e+04,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000,47150.000000
mean,26620.936437,123.662536,123.378517,0.284018,4.412216,3.116119,7.683712,4.025048,59.418425,70.812435,...,4.024833e+01,81.718981,1.399614e+01,9.550742,28.704999,0.910140,0.885329,41.050565,41.050273,0.389480
std,15111.690494,2710.883267,2710.694993,26.994757,54.074017,40.498946,185.589093,64.078530,717.287448,2021.915797,...,3.422734e+02,1815.443817,7.445932e+02,662.955031,579.939911,1.600399,1.003846,754.077033,754.077048,0.487638
min,0.000000,0.300000,0.030000,0.000000,1.000000,1.000000,1.000000,1.000000,0.010650,0.011145,...,7.444460e-15,0.030000,2.371314e-15,0.000000,0.000000,0.000235,0.000235,0.000089,0.000013,0.000000
25%,13435.250000,1.010000,1.010000,0.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,...,5.000000e-01,0.999886,1.719125e-04,0.000000,0.399876,1.000000,1.000000,0.800000,0.800000,0.000000
50%,27230.500000,5.140000,5.109950,0.000000,1.000000,1.000000,1.000000,2.000000,4.000000,4.000550,...,2.500000e+00,4.200000,5.000000e-02,0.000000,1.414034,1.000000,1.000000,3.000000,3.000000,0.000000
75%,39872.750000,45.330000,45.310000,0.000000,1.000000,1.000000,1.000000,2.000000,43.820000,44.040000,...,4.166917e+01,42.970000,7.579180e-01,0.000000,19.455000,1.000000,1.000000,41.117500,41.117500,1.000000
max,51679.000000,400000.013920,400000.000000,4175.770911,7915.000000,7003.000000,34038.000000,12213.000000,83333.353333,400000.000000,...,4.559295e+04,250000.000000,1.500000e+05,117851.116056,74500.000000,226.000000,128.000000,151000.000000,151000.000000,1.000000

In [53]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

def normalise(df):
    scaled_df = df.copy()
    scaled_df['in_degree'] = scaler.fit_transform(scaled_df['in_degree'].values.reshape(-1,1))
    scaled_df['out_degree']= scaler.fit_transform(scaled_df['out_degree'].values.reshape(-1,1))
    scaled_df['unique_in_degree']= scaler.fit_transform(scaled_df['out_degree'].values.reshape(-1,1))
    scaled_df['unique_out_degree']= scaler.fit_transform(scaled_df['out_degree'].values.reshape(-1,1))

    scaled_df['in_transaction_frequency']= scaler.fit_transform(scaled_df['in_transaction_frequency'].values.reshape(-1,1))
    scaled_df['out_transaction_frequency']= scaler.fit_transform(scaled_df['out_transaction_frequency'].values.reshape(-1,1))
    scaled_df['in_amount_frequency']= scaler.fit_transform(scaled_df['in_amount_frequency'].values.reshape(-1,1))
    scaled_df['out_amount_frequency']= scaler.fit_transform(scaled_df['out_amount_frequency'].values.reshape(-1,1))

    scaled_df['in_btc'] = scaler.fit_transform(scaled_df['in_btc'].values.reshape(-1,1))
    scaled_df['out_btc']= scaler.fit_transform(scaled_df['out_btc'].values.reshape(-1,1))
    scaled_df['balance']= scaler.fit_transform(scaled_df['balance'].values.reshape(-1,1))
    scaled_df['mean_in_btc']= scaler.fit_transform(scaled_df['mean_in_btc'].values.reshape(-1,1))
    scaled_df['mean_out_btc']= scaler.fit_transform(scaled_df['mean_out_btc'].values.reshape(-1,1))
    scaled_df['max_in_btc']= scaler.fit_transform(scaled_df['max_in_btc'].values.reshape(-1,1))
    scaled_df['min_in_btc']= scaler.fit_transform(scaled_df['min_in_btc'].values.reshape(-1,1))
    scaled_df['max_out_btc']= scaler.fit_transform(scaled_df['max_out_btc'].values.reshape(-1,1))
    scaled_df['min_out_btc']= scaler.fit_transform(scaled_df['min_out_btc'].values.reshape(-1,1))
    scaled_df['in_standard_deviation']= scaler.fit_transform(scaled_df['in_standard_deviation'].values.reshape(-1,1))
    scaled_df['out_standard_deviation']= scaler.fit_transform(scaled_df['out_standard_deviation'].values.reshape(-1,1))
    
    
    return scaled_df

In [54]:
def log_normalise(df):
    scaled_df = df.copy()
    scaled_df['in_degree'] = np.log1p(scaled_df['in_degree'].values.reshape(-1,1))
    scaled_df['out_degree']= np.log1p(scaled_df['out_degree'].values.reshape(-1,1))
    scaled_df['unique_in_degree']= np.log1p(scaled_df['unique_in_degree'].values.reshape(-1,1))
    scaled_df['unique_out_degree']= np.log1p(scaled_df['unique_out_degree'].values.reshape(-1,1))

    scaled_df['in_transaction_frequency']= np.log1p(scaled_df['in_transaction_frequency'].values.reshape(-1,1))
    scaled_df['out_transaction_frequency']= np.log1p(scaled_df['out_transaction_frequency'].values.reshape(-1,1))
    scaled_df['in_amount_frequency']= np.log1p(scaled_df['in_amount_frequency'].values.reshape(-1,1))
    scaled_df['out_amount_frequency']= np.log1p(scaled_df['out_amount_frequency'].values.reshape(-1,1))

    scaled_df['in_btc'] = np.log1p(scaled_df['in_btc'].values.reshape(-1,1))
    scaled_df['out_btc']= np.log1p(scaled_df['out_btc'].values.reshape(-1,1))
    scaled_df['balance']= np.log1p(scaled_df['balance'].values.reshape(-1,1))
    scaled_df['mean_in_btc']= np.log1p(scaled_df['mean_in_btc'].values.reshape(-1,1))
    scaled_df['mean_out_btc']= np.log1p(scaled_df['mean_out_btc'].values.reshape(-1,1))
    scaled_df['max_in_btc']= np.log1p(scaled_df['max_in_btc'].values.reshape(-1,1))
    scaled_df['min_in_btc']= np.log1p(scaled_df['min_in_btc'].values.reshape(-1,1))
    scaled_df['max_out_btc']= np.log1p(scaled_df['max_out_btc'].values.reshape(-1,1))
    scaled_df['min_out_btc']= np.log1p(scaled_df['min_out_btc'].values.reshape(-1,1))
    scaled_df['in_standard_deviation']= np.log1p(scaled_df['in_standard_deviation'].values.reshape(-1,1))
    scaled_df['out_standard_deviation']= np.log1p(scaled_df['out_standard_deviation'].values.reshape(-1,1))
    
    return scaled_df

In [55]:
# df_scaled = normalise(df)
scaled_df = log_normalise(df)
scaled_df

,index,address,in_btc,out_btc,balance,in_degree,out_degree,unique_in_degree,unique_out_degree,mean_in_btc,...,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
0,0,19snqSYnDSC4mDbv3pJuYgYqm5ctqwAxnm,3.931826,3.931826,0.0,0.693147,0.693147,0.693147,1.098612,3.931826,...,3.931826,3.648811,2.607940,0.000000,2.597412,0.105361,0.105361,1.880313,1.880313,0
1,1,1FeGY25MSKtnwVNGrnbwLsecBpBYrMQ6Kx,3.931826,3.931826,0.0,0.693147,0.693147,0.693147,1.098612,3.931826,...,3.931826,3.784454,2.077988,0.000000,2.945050,0.693147,0.693147,3.931826,3.931826,0
2,2,1A1nkBK7tfnVRtVbyiirEWRcayQtSTBCsW,2.317474,2.317474,0.0,0.693147,0.693147,0.693147,1.098612,2.317474,...,2.317474,2.163323,0.896088,0.000000,1.417066,0.693147,0.693147,2.317474,2.317474,0
3,3,18wHa1PLzoU4ToemBZn2czZbVEbyZJ2gSi,5.832615,5.832615,0.0,0.693147,0.693147,0.693147,1.098612,5.832615,...,5.832615,5.832469,0.048790,0.000000,5.142102,0.693147,0.693147,5.832615,5.832615,0
4,4,188sYyuK756uEsq5LTk9tiXyJHeEjxKT5c,4.856007,4.856007,0.0,0.693147,0.693147,0.693147,1.098612,4.856007,...,4.856007,4.855618,0.048790,0.000000,4.169838,0.693147,0.693147,4.856007,4.856007,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47145,51675,1NEDowT7w4kMFhwv2EARsvj98UPTM88n8E,4.136377,4.136377,0.0,3.912023,3.912023,1.609438,4.574711,0.813880,...,0.102736,2.397895,0.000004,0.949553,0.702704,0.236103,0.236103,0.288670,0.288670,1
47146,51676,1NEehsUcB3e5gzXNngjYtpgBEKZDLdm1wR,1.098612,1.098612,0.0,0.693147,0.693147,1.609438,0.693147,1.098612,...,0.047628,1.098548,0.000193,0.283607,0.693051,0.693147,0.693147,1.098612,1.098612,1
47147,51677,1NEgxsitmSW3Spyv9GRGZZgvRYGU84oBzb,0.693147,0.693147,0.0,0.693147,0.693147,1.386294,1.098612,0.693147,...,0.006492,0.692957,0.000007,0.375212,0.386035,0.693147,0.693147,0.693147,0.693147,1
47148,51678,1NeiGxRsrXXg1yv81Ch6QEEVft46wpEY2G,1.223775,1.223775,0.0,1.098612,1.098612,1.098612,1.609438,0.788457,...,0.788457,0.788406,0.000013,0.000000,0.448072,0.154151,0.154151,0.182322,0.182322,1
47149,51679,1NEkqoKaJB98ZidfDM5UvX81kabcY5RQVX,0.418316,0.418316,0.0,0.693147,0.693147,0.693147,0.693147,0.418316,...,0.418316,0.418180,0.000206,0.000000,0.230710,0.693147,0.693147,0.418316,0.418316,1

In [56]:
scaled_df = scaled_df.drop([
            "address",
            "in_btc",  # Total BTC received or Inbound Amount
            "out_btc",  # Total BTC sent or Outbound Amount
            "in_degree",  # Total number of inbound transactions
            "out_degree",  # Total number of outbound transactions
            "first_active",
            "last_active",
        ],axis = 1)

In [57]:
scaled_df

,index,balance,unique_in_degree,unique_out_degree,mean_in_btc,mean_out_btc,max_in_btc,min_in_btc,max_out_btc,min_out_btc,in_standard_deviation,out_standard_deviation,in_transaction_frequency,out_transaction_frequency,in_amount_frequency,out_amount_frequency,is_Malicious
0,0,0.0,0.693147,1.098612,3.931826,3.931826,3.931826,3.931826,3.648811,2.607940,0.000000,2.597412,0.105361,0.105361,1.880313,1.880313,0
1,1,0.0,0.693147,1.098612,3.931826,3.931826,3.931826,3.931826,3.784454,2.077988,0.000000,2.945050,0.693147,0.693147,3.931826,3.931826,0
2,2,0.0,0.693147,1.098612,2.317474,2.317474,2.317474,2.317474,2.163323,0.896088,0.000000,1.417066,0.693147,0.693147,2.317474,2.317474,0
3,3,0.0,0.693147,1.098612,5.832615,5.832615,5.832615,5.832615,5.832469,0.048790,0.000000,5.142102,0.693147,0.693147,5.832615,5.832615,0
4,4,0.0,0.693147,1.098612,4.856007,4.856007,4.856007,4.856007,4.855618,0.048790,0.000000,4.169838,0.693147,0.693147,4.856007,4.856007,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47145,51675,0.0,1.609438,4.574711,0.813880,0.813880,2.397895,0.102736,2.397895,0.000004,0.949553,0.702704,0.236103,0.236103,0.288670,0.288670,1
47146,51676,0.0,1.609438,0.693147,1.098612,1.098612,0.680877,0.047628,1.098548,0.000193,0.283607,0.693051,0.693147,0.693147,1.098612,1.098612,1
47147,51677,0.0,1.386294,1.098612,0.693147,0.693147,0.681682,0.006492,0.692957,0.000007,0.375212,0.386035,0.693147,0.693147,0.693147,0.693147,1
47148,51678,0.0,1.098612,1.609438,0.788457,0.788457,0.788457,0.788457,0.788406,0.000013,0.000000,0.448072,0.154151,0.154151,0.182322,0.182322,1
47149,51679,0.0,0.693147,0.693147,0.418316,0.418316,0.418316,0.418316,0.418180,0.000206,0.000000,0.230710,0.693147,0.693147,0.418316,0.418316,1

In [59]:
# import seaborn as sns
# import matplotlib.pyplot as plt

# temp=[1,2,3,4,5,6,7,3,2,3,3,4,5,]
# # sns.set(style="whitegrid")
# # sns.boxplot(x =df['balance'],showfliers=False)
# fig, ax = plt.subplots()
# sns.boxplot(data=df["is_malicious"], orient='vertical')

### Decision Tree

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_df.iloc[:,:-1], scaled_df['is_malicious'], test_size = 0.2, random_state=0)

KeyError: 'is_malicious'

In [ ]:
X_train

In [ ]:
print(f"For Test Data: Out of {y_test.size}, {y_test.sum()} are Malicious.")

In [ ]:
print(f"For Train Data: Out of {y_train.size}, {y_train.sum()} are Malicious.")

In [ ]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
def decision_tree_classification(X_train, y_train, X_test, y_test):
    # initialize object for DecisionTreeClassifier class
    dt_classifier = DecisionTreeClassifier()
    # train model by using fit method
    print("Model training starts........")
    dt_classifier.fit(X_train, y_train.values.ravel())
    print("Model training completed")
    acc_score = dt_classifier.score(X_test, y_test)
    print(f'Accuracy of model on test dataset :- {acc_score}')
    # predict result using test dataset
    y_pred = dt_classifier.predict(X_test)
    # confusion matrix
    print(f"Confusion Matrix :- \n {confusion_matrix(y_test, y_pred)}")
    # classification report for f1-score
    print(f"Classification Report :- \n {classification_report(y_test, y_pred)}")
    return dt_classifier

In [ ]:
dt_classifier=decision_tree_classification(X_train, y_train, X_test, y_test)

### Testing

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

def normalise_list(row):
    nor_row = []
    for i in row:
        entry = np.log1p(i)
        nor_row.append(entry)
    print(nor_row)
    return np.array(nor_row)

In [ ]:
mal_row = [2475.43569884
,221484,239569,26.87299832612703,29.722567950168337,2999.9999999999995,34.15016218,1198.5016117600003,37.04971010360595,253.45334695203664,162.09956539510037,182.53114186851212,165.060553633218,4905.159069898581,4906.023521255726]

In [ ]:
mal_row = normalise_list(mal_row)
# print(mal_row)

model_prediction = dt_classifier.predict(mal_row.reshape(1,-1))
print(f"Malicious: {model_prediction[0]==1}")

In [ ]:
arr = np.array(mal_row)
arr

In [ ]:
arr = arr.reshape(1,-1)

In [ ]:
model_prediction = dt_classifier.predict(arr)
print(model_prediction)
# [-0.010521,1.132977,1.132977, -0.081087, -0.034401, -0.036376, -0.117276, -0.039505, -0.018797, -0.012016, -0.047740, -0.402302, -0.616660, -0.053995, -0.053995]

In [ ]:
import pickle
with open('bitcoin_malicious_address_prediction.pickle','wb') as f:
    pickle.dump(dt_classifier,f)