In [1]:
import pandas as pd

In [2]:
from glob import glob 
data_files = sorted(glob('temp/DG_out_*.csv'))
type(data_files)

list

In [3]:
df = pd.concat((pd.read_csv(file) for file in data_files))
df

,Unnamed: 0,tx_hash,indegree,outdegree,in_btc,out_btc,total_btc,mean_in_btc,mean_out_btc,in_malicious,out_malicious,is_malicious,out_and_tx_malicious,all_malicious
0,0,0437cd7f8525ceed2324359c2d0ba26006d92d856a9c20...,0,1,0.000000,50.000000,50.000000,0.000000,50.000000,0,0,0,0,0
1,1,f4184fc596403b9d638783cf57adfe4c75c605f6356fbc...,1,2,50.000000,50.000000,100.000000,50.000000,25.000000,0,0,0,0,0
2,2,ea44e97271691990157559d0bdd9959e02790c34db6c00...,1,1,10.000000,10.000000,20.000000,10.000000,10.000000,0,0,0,0,0
3,3,a16f3ce4dd5deb92d98ef5cf8afeaf0775ebca408f708b...,1,1,40.000000,30.000000,70.000000,40.000000,30.000000,0,0,0,0,0
4,4,591e91f809d716912ca1d4a9295e70c3e78bab077683f7...,1,2,30.000000,30.000000,60.000000,30.000000,15.000000,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,7999995,c330995c3490ba7d168386b1bb7ea209c3066f9a4068fc...,1,1,21.797062,21.797062,43.594124,21.797062,21.797062,0,0,0,0,0
999996,7999996,f789084470b19d6379456a98501db719a037d0d84a77ef...,1,2,28.202966,28.202966,56.405932,28.202966,14.101483,0,0,0,0,0
999997,7999997,10c10e5924afa00423ed2bb6a7bca2ddbb3752844202a4...,1,2,32.457045,32.457045,64.914090,32.457045,16.228523,0,0,0,0,0
999998,7999998,8811a575725df2cca304be3131a72a6e793b7a223ebde3...,1,2,29.031518,29.031018,58.062536,29.031518,14.515509,0,0,0,0,0
999999,7999999,6f62dcf02063b54d457d4ffa72c278b3235a7691b4540d...,1,2,11.819780,11.819280,23.639060,11.819780,5.909640,0,0,0,0,0

In [4]:
in_malicious_0_count = df['in_malicious'].value_counts()[0]
in_malicious_1_count = df['in_malicious'].value_counts()[1]
out_malicious_0_count = df['out_malicious'].value_counts()[0]
out_malicious_1_count = df['out_malicious'].value_counts()[1]
is_malicious_0 = df['is_malicious'].value_counts()[0]
is_malicious_1 = df['is_malicious'].value_counts()[1]
out_and_tx_malicious_0 = df['out_and_tx_malicious'].value_counts()[0]
out_and_tx_malicious_1 = df['out_and_tx_malicious'].value_counts()[1]
all_malicious_0 = df['all_malicious'].value_counts()[0]
all_malicious_1 = df['all_malicious'].value_counts()[1]

In [5]:
print(in_malicious_0_count)
print(in_malicious_1_count)
print(out_malicious_0_count)
print(out_malicious_1_count)
print(is_malicious_0)
print(is_malicious_1)
print(out_and_tx_malicious_0)
print(out_and_tx_malicious_1)
print(all_malicious_0)
print(all_malicious_1)

7999003
997
7999972
28
7999973
27
7999948
52
7998954
1046

In [6]:
df.isnull().sum()

Unnamed: 0              0
tx_hash                 0
indegree                0
outdegree               0
in_btc                  0
out_btc                 0
total_btc               0
mean_in_btc             0
mean_out_btc            0
in_malicious            0
out_malicious           0
is_malicious            0
out_and_tx_malicious    0
all_malicious           0
dtype: int64

In [3]:
df_malicious_only = pd.DataFrame()
df_malicious_only

Empty DataFrame
Columns: []
Index: []

In [11]:
for i in data_files:
    df = pd.read_csv(i)
    print(str(i) + 'ith dataframe len = '+ str(len(df)))

temp1\DG_out_0.csvith dataframe len = 1000000
temp1\DG_out_1.csvith dataframe len = 1000000
temp1\DG_out_2.csvith dataframe len = 1000000

KeyboardInterrupt:

In [37]:
df_temp1 = pd.DataFrame()
df_temp2 = pd.read_csv('temp/DG_out_0.csv')
for i in range(len(df_temp2)):
    if(df_temp2.iloc[i]['out_and_tx_malicious'] == 1):
        print('here')
       
        df_temp1 = df_temp1.append(df_temp2.iloc[i],ignore_index=True)
        

df_temp1

here
here
here

,Unnamed: 0,all_malicious,in_btc,in_malicious,indegree,is_malicious,mean_in_btc,mean_out_btc,out_and_tx_malicious,out_btc,out_malicious,outdegree,total_btc,tx_hash
0,385224.0,1.0,25000.620000,0.0,478.0,1.0,52.302552,12500.005000,1.0,25000.010000,0.0,2.0,50000.630000,4885ddf124a0f97b5a3775a12de0274d342d12842ebe59...
1,385245.0,1.0,1720.151291,0.0,83.0,0.0,20.724714,860.005646,1.0,1720.011291,1.0,2.0,3440.162582,48819d9d09c34df32feb1de0c4a54b9303031548cdd16c...
2,677395.0,1.0,25000.000000,0.0,1.0,0.0,25000.000000,12500.000000,1.0,25000.000000,1.0,2.0,50000.000000,d878b5784c2c1f6642d83faeab86e97faba758b2733a57...

In [9]:
for i in data_files:
    df = pd.read_csv(i)
    print('Processing ' + str(i) + 'dataframe')
    
    for j in range(len(df)):
        if(df.iloc[j]['out_and_tx_malicious'] == 1):
            df_malicious_only =  df_malicious_only.append(df.iloc[j],ignore_index=True)
    print(str(i) + 'th datafile done')
    
print(df_malicious_only)

df_malicious_only.to_csv('temp/maliciousOnly.csv', encoding='utf-8')

Processing temp\DG_out_0.csvdataframe
temp\DG_out_0.csvth datafile done
Processing temp\DG_out_1.csvdataframe
temp\DG_out_1.csvth datafile done
Processing temp\DG_out_10.csvdataframe
temp\DG_out_10.csvth datafile done
Processing temp\DG_out_11.csvdataframe
temp\DG_out_11.csvth datafile done
Processing temp\DG_out_12.csvdataframe
temp\DG_out_12.csvth datafile done
Processing temp\DG_out_13.csvdataframe
temp\DG_out_13.csvth datafile done
Processing temp\DG_out_14.csvdataframe
temp\DG_out_14.csvth datafile done
Processing temp\DG_out_15.csvdataframe
temp\DG_out_15.csvth datafile done
Processing temp\DG_out_16.csvdataframe
temp\DG_out_16.csvth datafile done
Processing temp\DG_out_17.csvdataframe
temp\DG_out_17.csvth datafile done
Processing temp\DG_out_18.csvdataframe
temp\DG_out_18.csvth datafile done
Processing temp\DG_out_19.csvdataframe
temp\DG_out_19.csvth datafile done
Processing temp\DG_out_2.csvdataframe
temp\DG_out_2.csvth datafile done
Processing temp\DG_out_20.csvdataframe
temp\DG_out_20.csvth datafile done
Processing temp\DG_out_21.csvdataframe
temp\DG_out_21.csvth datafile done
Processing temp\DG_out_22.csvdataframe
temp\DG_out_22.csvth datafile done
Processing temp\DG_out_23.csvdataframe
temp\DG_out_23.csvth datafile done
Processing temp\DG_out_24.csvdataframe
temp\DG_out_24.csvth datafile done
Processing temp\DG_out_25.csvdataframe
temp\DG_out_25.csvth datafile done
Processing temp\DG_out_26.csvdataframe
temp\DG_out_26.csvth datafile done
Processing temp\DG_out_27.csvdataframe
temp\DG_out_27.csvth datafile done
Processing temp\DG_out_28.csvdataframe
temp\DG_out_28.csvth datafile done
Processing temp\DG_out_29.csvdataframe
temp\DG_out_29.csvth datafile done
Processing temp\DG_out_3.csvdataframe
temp\DG_out_3.csvth datafile done
Processing temp\DG_out_30.csvdataframe
temp\DG_out_30.csvth datafile done
Processing temp\DG_out_4.csvdataframe
temp\DG_out_4.csvth datafile done
Processing temp\DG_out_5.csvdataframe
temp\DG_out_5.csvth datafile done
Processing temp\DG_out_6.csvdataframe
temp\DG_out_6.csvth datafile done
Processing temp\DG_out_7.csvdataframe
temp\DG_out_7.csvth datafile done
Processing temp\DG_out_8.csvdataframe
temp\DG_out_8.csvth datafile done
Processing temp\DG_out_9.csvdataframe
temp\DG_out_9.csvth datafile done
     Unnamed: 0  all_malicious        in_btc  in_malicious  indegree  \
0      385224.0            1.0  25000.620000           0.0     478.0
1      385245.0            1.0   1720.151291           0.0      83.0
2      677395.0            1.0  25000.000000           0.0       1.0
3    10910788.0            1.0      0.688450           0.0       5.0
4    10911101.0            1.0      0.225000           0.0       2.0
..          ...            ...           ...           ...       ...
103   8863543.0            1.0    108.835343           0.0       4.0
104   8875401.0            1.0    118.901583           0.0       2.0
105   8898023.0            1.0      8.830343           0.0       1.0
106   9154941.0            1.0     22.892783           0.0       2.0
107   9434941.0            1.0    492.043821           0.0       3.0

     is_malicious   mean_in_btc  mean_out_btc  out_and_tx_malicious  \
0             1.0     52.302552  12500.005000                   1.0
1             0.0     20.724714    860.005646                   1.0
2             0.0  25000.000000  12500.000000                   1.0
3             0.0      0.137690      0.680000                   1.0
4             0.0      0.112500      0.220000                   1.0
..            ...           ...           ...                   ...
103           1.0     27.208836     54.415171                   1.0
104           1.0     59.450792     59.448292                   1.0
105           0.0      8.830343      4.414921                   1.0
106           0.0     11.446392     11.446292                   1.0
107           0.0    164.014607    246.021910                   1.0

          out_btc  out_malicious  outdegree     total_btc  \
0    25000.010000            0.0        2.0  50000.630000
1     1720.011291            1.0        2.0   3440.162582
2    25000.000000            1.0        2.0  50000.000000
3        0.680000            1.0        1.0      1.368450
4        0.220000            1.0        1.0      0.445000
..            ...            ...        ...           ...
103    108.830343            0.0        2.0    217.665686
104    118.896583            0.0        2.0    237.798167
105      8.829843            1.0        2.0     17.660186
106     22.892583            1.0        2.0     45.785367
107    492.043821            1.0        2.0    984.087642

                                               tx_hash
0    4885ddf124a0f97b5a3775a12de0274d342d12842ebe59...
1    48819d9d09c34df32feb1de0c4a54b9303031548cdd16c...
2    d878b5784c2c1f6642d83faeab86e97faba758b2733a57...
3    e3c8d10c304139a162f3147df38e38aa2f3d54ce5029b7...
4    51654fc7b8c059252e5104a532a6395f255c8c0b23d24b...
..                                                 ...
103  3a66ebef43041f230e799f1efd3a93e41f875c718da683...
104  0197692748ba894697a0a48fdfdb3e72f3275b079005ef...
105  abfc344cb5cfc51ce924a3d71fdfca158f390185feaaa2...
106  f5f39c652586b1a623f8f1549d793ff9724e5583c25882...
107  cc827939ae3abec82f24f25e5c40518ff0845159b64374...

[108 rows x 14 columns]

In [5]:
def batch(start, end):
    print(start, end)
    for k in range(start,end):
        i = data_files[k]
        df = pd.read_csv(i)
        print('Processing ' + str(i) + 'dataframe')

        for j in range(len(df)):
            
            if(df.iloc[j]['out_and_tx_malicious'] == 1):
                df_malicious_only =  df_malicious_only.append(df.iloc[j],ignore_index=True)
                
        print(str(i) + 'th datafile done')

    print(df_malicious_only)

In [8]:
import threading
import os

global df_malicious_only
df_malicious_only = pd.DataFrame()

t1 = threading.Thread(target=batch, args=(0,1,))
t2 = threading.Thread(target=batch, args=(1,2,))
# starting thread 1
t1.start()
# starting thread 2
t2.start()

# wait until thread 1 is completely executed
t1.join()
# wait until thread 2 is completely executed
t2.join()

df_malicious_only

01 2
 1
Processing temp\DG_out_0.csvdataframeProcessing temp\DG_out_1.csvdataframe

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MSI\AppData\Local\Temp\ipykernel_5664\1266657404.py", line 11, in batch
    df_malicious_only =  df_malicious_only.append(df.iloc[j],ignore_index=True)
UnboundLocalError: local variable 'df_malicious_only' referenced before assignment

temp\DG_out_1.csvth datafile done

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MSI\AppData\Local\Temp\ipykernel_5664\1266657404.py", line 15, in batch
    print(df_malicious_only)
UnboundLocalError: local variable 'df_malicious_only' referenced before assignment

Empty DataFrame
Columns: []
Index: []

In [19]:
# Merging malicious transactions data with original data
# reading two csv files
import pandas as pd
file1 = pd.read_csv('temp/DG_out_0.csv')
file1['out_and_tx_malicious'] = file1['out_and_tx_malicious ']
file1 = file1.drop('out_and_tx_malicious ', axis=1)
file2 = pd.read_csv('temp/maliciousOnly.csv')


merged = file1.append(file2)

merged

,Unnamed: 0,tx_hash,indegree,outdegree,in_btc,out_btc,total_btc,mean_in_btc,mean_out_btc,in_malicious,out_malicious,is_malicious,all_malicious,out_and_tx_malicious,Unnamed: 0.1
0,0,0437cd7f8525ceed2324359c2d0ba26006d92d856a9c20...,0.0,1.0,0.000000,50.000000,50.000000,0.000000,50.000000,0.0,0.0,0.0,0.0,0.0,NaN
1,1,f4184fc596403b9d638783cf57adfe4c75c605f6356fbc...,1.0,2.0,50.000000,50.000000,100.000000,50.000000,25.000000,0.0,0.0,0.0,0.0,0.0,NaN
2,2,ea44e97271691990157559d0bdd9959e02790c34db6c00...,1.0,1.0,10.000000,10.000000,20.000000,10.000000,10.000000,0.0,0.0,0.0,0.0,0.0,NaN
3,3,a16f3ce4dd5deb92d98ef5cf8afeaf0775ebca408f708b...,1.0,1.0,40.000000,30.000000,70.000000,40.000000,30.000000,0.0,0.0,0.0,0.0,0.0,NaN
4,4,591e91f809d716912ca1d4a9295e70c3e78bab077683f7...,1.0,2.0,30.000000,30.000000,60.000000,30.000000,15.000000,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,103,3a66ebef43041f230e799f1efd3a93e41f875c718da683...,4.0,2.0,108.835343,108.830343,217.665686,27.208836,54.415171,0.0,0.0,1.0,1.0,1.0,8863543.0
104,104,0197692748ba894697a0a48fdfdb3e72f3275b079005ef...,2.0,2.0,118.901583,118.896583,237.798167,59.450792,59.448292,0.0,0.0,1.0,1.0,1.0,8875401.0
105,105,abfc344cb5cfc51ce924a3d71fdfca158f390185feaaa2...,1.0,2.0,8.830343,8.829843,17.660186,8.830343,4.414921,0.0,1.0,0.0,1.0,1.0,8898023.0
106,106,f5f39c652586b1a623f8f1549d793ff9724e5583c25882...,2.0,2.0,22.892783,22.892583,45.785367,11.446392,11.446292,0.0,1.0,0.0,1.0,1.0,9154941.0
107,107,cc827939ae3abec82f24f25e5c40518ff0845159b64374...,3.0,2.0,492.043821,492.043821,984.087642,164.014607,246.021910,0.0,1.0,0.0,1.0,1.0,9434941.0

In [5]:
merged.to_csv('temp/FinalDataset.csv', encoding='utf-8')

In [6]:
merged

,Unnamed: 0,tx_hash,indegree,outdegree,in_btc,out_btc,total_btc,mean_in_btc,mean_out_btc,in_malicious,out_malicious,is_malicious,out_and_tx_malicious,all_malicious,Unnamed: 0.1,out_and_tx_malicious
0,0,0437cd7f8525ceed2324359c2d0ba26006d92d856a9c20...,0.0,1.0,0.000000,50.000000,50.000000,0.000000,50.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,1,f4184fc596403b9d638783cf57adfe4c75c605f6356fbc...,1.0,2.0,50.000000,50.000000,100.000000,50.000000,25.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,2,ea44e97271691990157559d0bdd9959e02790c34db6c00...,1.0,1.0,10.000000,10.000000,20.000000,10.000000,10.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,3,a16f3ce4dd5deb92d98ef5cf8afeaf0775ebca408f708b...,1.0,1.0,40.000000,30.000000,70.000000,40.000000,30.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,4,591e91f809d716912ca1d4a9295e70c3e78bab077683f7...,1.0,2.0,30.000000,30.000000,60.000000,30.000000,15.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,103,3a66ebef43041f230e799f1efd3a93e41f875c718da683...,4.0,2.0,108.835343,108.830343,217.665686,27.208836,54.415171,0.0,0.0,1.0,NaN,1.0,8863543.0,1.0
104,104,0197692748ba894697a0a48fdfdb3e72f3275b079005ef...,2.0,2.0,118.901583,118.896583,237.798167,59.450792,59.448292,0.0,0.0,1.0,NaN,1.0,8875401.0,1.0
105,105,abfc344cb5cfc51ce924a3d71fdfca158f390185feaaa2...,1.0,2.0,8.830343,8.829843,17.660186,8.830343,4.414921,0.0,1.0,0.0,NaN,1.0,8898023.0,1.0
106,106,f5f39c652586b1a623f8f1549d793ff9724e5583c25882...,2.0,2.0,22.892783,22.892583,45.785367,11.446392,11.446292,0.0,1.0,0.0,NaN,1.0,9154941.0,1.0
107,107,cc827939ae3abec82f24f25e5c40518ff0845159b64374...,3.0,2.0,492.043821,492.043821,984.087642,164.014607,246.021910,0.0,1.0,0.0,NaN,1.0,9434941.0,1.0

In [20]:
merged = merged.drop('Unnamed: 0',axis=1)
merged

,tx_hash,indegree,outdegree,in_btc,out_btc,total_btc,mean_in_btc,mean_out_btc,in_malicious,out_malicious,is_malicious,all_malicious,out_and_tx_malicious,Unnamed: 0.1
0,0437cd7f8525ceed2324359c2d0ba26006d92d856a9c20...,0.0,1.0,0.000000,50.000000,50.000000,0.000000,50.000000,0.0,0.0,0.0,0.0,0.0,NaN
1,f4184fc596403b9d638783cf57adfe4c75c605f6356fbc...,1.0,2.0,50.000000,50.000000,100.000000,50.000000,25.000000,0.0,0.0,0.0,0.0,0.0,NaN
2,ea44e97271691990157559d0bdd9959e02790c34db6c00...,1.0,1.0,10.000000,10.000000,20.000000,10.000000,10.000000,0.0,0.0,0.0,0.0,0.0,NaN
3,a16f3ce4dd5deb92d98ef5cf8afeaf0775ebca408f708b...,1.0,1.0,40.000000,30.000000,70.000000,40.000000,30.000000,0.0,0.0,0.0,0.0,0.0,NaN
4,591e91f809d716912ca1d4a9295e70c3e78bab077683f7...,1.0,2.0,30.000000,30.000000,60.000000,30.000000,15.000000,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,3a66ebef43041f230e799f1efd3a93e41f875c718da683...,4.0,2.0,108.835343,108.830343,217.665686,27.208836,54.415171,0.0,0.0,1.0,1.0,1.0,8863543.0
104,0197692748ba894697a0a48fdfdb3e72f3275b079005ef...,2.0,2.0,118.901583,118.896583,237.798167,59.450792,59.448292,0.0,0.0,1.0,1.0,1.0,8875401.0
105,abfc344cb5cfc51ce924a3d71fdfca158f390185feaaa2...,1.0,2.0,8.830343,8.829843,17.660186,8.830343,4.414921,0.0,1.0,0.0,1.0,1.0,8898023.0
106,f5f39c652586b1a623f8f1549d793ff9724e5583c25882...,2.0,2.0,22.892783,22.892583,45.785367,11.446392,11.446292,0.0,1.0,0.0,1.0,1.0,9154941.0
107,cc827939ae3abec82f24f25e5c40518ff0845159b64374...,3.0,2.0,492.043821,492.043821,984.087642,164.014607,246.021910,0.0,1.0,0.0,1.0,1.0,9434941.0

In [21]:
merged = merged.drop('Unnamed: 0.1',axis=1)
merged

,tx_hash,indegree,outdegree,in_btc,out_btc,total_btc,mean_in_btc,mean_out_btc,in_malicious,out_malicious,is_malicious,all_malicious,out_and_tx_malicious
0,0437cd7f8525ceed2324359c2d0ba26006d92d856a9c20...,0.0,1.0,0.000000,50.000000,50.000000,0.000000,50.000000,0.0,0.0,0.0,0.0,0.0
1,f4184fc596403b9d638783cf57adfe4c75c605f6356fbc...,1.0,2.0,50.000000,50.000000,100.000000,50.000000,25.000000,0.0,0.0,0.0,0.0,0.0
2,ea44e97271691990157559d0bdd9959e02790c34db6c00...,1.0,1.0,10.000000,10.000000,20.000000,10.000000,10.000000,0.0,0.0,0.0,0.0,0.0
3,a16f3ce4dd5deb92d98ef5cf8afeaf0775ebca408f708b...,1.0,1.0,40.000000,30.000000,70.000000,40.000000,30.000000,0.0,0.0,0.0,0.0,0.0
4,591e91f809d716912ca1d4a9295e70c3e78bab077683f7...,1.0,2.0,30.000000,30.000000,60.000000,30.000000,15.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,3a66ebef43041f230e799f1efd3a93e41f875c718da683...,4.0,2.0,108.835343,108.830343,217.665686,27.208836,54.415171,0.0,0.0,1.0,1.0,1.0
104,0197692748ba894697a0a48fdfdb3e72f3275b079005ef...,2.0,2.0,118.901583,118.896583,237.798167,59.450792,59.448292,0.0,0.0,1.0,1.0,1.0
105,abfc344cb5cfc51ce924a3d71fdfca158f390185feaaa2...,1.0,2.0,8.830343,8.829843,17.660186,8.830343,4.414921,0.0,1.0,0.0,1.0,1.0
106,f5f39c652586b1a623f8f1549d793ff9724e5583c25882...,2.0,2.0,22.892783,22.892583,45.785367,11.446392,11.446292,0.0,1.0,0.0,1.0,1.0
107,cc827939ae3abec82f24f25e5c40518ff0845159b64374...,3.0,2.0,492.043821,492.043821,984.087642,164.014607,246.021910,0.0,1.0,0.0,1.0,1.0

In [22]:
merged.to_csv('temp/Final_Dataset.csv', encoding='utf-8')