In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("./raw_dataset/BitcoinHeistData.csv")

In [3]:
df

,address,year,day,length,weight,count,looped,neighbors,income,label
0,111K8kZAEnJg245r2cM6y9zgJGHZtJPy6,2017,11,18,0.008333,1,0,2,1.000500e+08,princetonCerber
1,1123pJv8jzeFQaCV4w644pzQJzVWay2zcA,2016,132,44,0.000244,1,0,1,1.000000e+08,princetonLocky
2,112536im7hy6wtKbpH1qYDWtTyMRAcA2p7,2016,246,0,1.000000,1,0,2,2.000000e+08,princetonCerber
3,1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7,2016,322,72,0.003906,1,0,2,7.120000e+07,princetonCerber
4,1129TSjKtx65E35GiUo4AYVeyo48twbrGX,2016,238,144,0.072848,456,0,1,2.000000e+08,princetonLocky
...,...,...,...,...,...,...,...,...,...,...
2916692,12D3trgho1vJ4mGtWBRPyHdMJK96TRYSry,2018,330,0,0.111111,1,0,1,1.255809e+09,white
2916693,1P7PputTcVkhXBmXBvSD9MJ3UYPsiou1u2,2018,330,0,1.000000,1,0,1,4.409699e+07,white
2916694,1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw,2018,330,2,12.000000,6,6,35,2.398267e+09,white
2916695,15iPUJsRNZQZHmZZVwmQ63srsmughCXV4a,2018,330,0,0.500000,1,0,1,1.780427e+08,white
2916696,3LFFBxp15h9KSFtaw55np8eP5fv6kdK17e,2018,330,144,0.073972,6800,0,2,1.123500e+08,white

In [25]:
df=df[df["label"]!="white"]

In [32]:
df

,address,year,day,length,weight,count,looped,neighbors,income,label
0,111K8kZAEnJg245r2cM6y9zgJGHZtJPy6,2017,11,18,0.008333,1,0,2,1.000500e+08,princetonCerber
1,1123pJv8jzeFQaCV4w644pzQJzVWay2zcA,2016,132,44,0.000244,1,0,1,1.000000e+08,princetonLocky
2,112536im7hy6wtKbpH1qYDWtTyMRAcA2p7,2016,246,0,1.000000,1,0,2,2.000000e+08,princetonCerber
3,1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7,2016,322,72,0.003906,1,0,2,7.120000e+07,princetonCerber
4,1129TSjKtx65E35GiUo4AYVeyo48twbrGX,2016,238,144,0.072848,456,0,1,2.000000e+08,princetonLocky
...,...,...,...,...,...,...,...,...,...,...
41408,35iCvpMMnUWcSWrYtLJLXqe9xo5CYEWRhw,2017,76,144,1.375002,8076,8073,6,5.726876e+08,montrealAPT
41409,377CY1m8W2qbQQX5HHjziimdh2faGjDeLv,2016,259,2,1.500000,2,0,2,7.449526e+07,montrealAPT
41410,377CY1m8W2qbQQX5HHjziimdh2faGjDeLv,2016,277,0,0.500000,1,0,2,5.714286e+07,montrealAPT
41411,377CY1m8W2qbQQX5HHjziimdh2faGjDeLv,2016,271,6,0.125000,1,0,2,1.000000e+08,montrealAPT
41412,377CY1m8W2qbQQX5HHjziimdh2faGjDeLv,2016,278,144,0.309727,4882,0,1,1.000000e+09,montrealAPT

In [38]:
addresses=df["address"].unique()

In [40]:
addresses.size

20849

In [42]:
import numpy as np

In [45]:
np.savetxt('./cleaned_dataset/heist_addresses.csv', addresses, delimiter=',', fmt='%s', header="address")